
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Scanner;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Or = 34;
  public static final int Coma = 8;
  public static final int Llave_c = 29;
  public static final int Literal = 23;
  public static final int Llave_a = 28;
  public static final int If = 19;
  public static final int Void = 17;
  public static final int Default = 10;
  public static final int Menos = 38;
  public static final int Mas = 37;
  public static final int Else = 20;
  public static final int Read = 44;
  public static final int Break = 4;
  public static final int Asignacion = 33;
  public static final int Corchete_c = 27;
  public static final int Corchete_a = 26;
  public static final int Long = 13;
  public static final int Relacionales = 21;
  public static final int Return = 14;
  public static final int While = 18;
  public static final int Division = 40;
  public static final int Scolon = 31;
  public static final int Int = 3;
  public static final int Parentesis_c = 25;
  public static final int Modulo = 41;
  public static final int Parentesis_a = 24;
  public static final int For = 12;
  public static final int EOF = 0;
  public static final int Not = 36;
  public static final int And = 35;
  public static final int error = 1;
  public static final int Switch = 16;
  public static final int Linea = 2;
  public static final int Char = 6;
  public static final int Unarios = 42;
  public static final int Do = 11;
  public static final int LEX_ERROR = 46;
  public static final int Continue = 9;
  public static final int Case = 5;
  public static final int Short = 15;
  public static final int Dos_puntos = 45;
  public static final int Const = 7;
  public static final int Identificador = 22;
  public static final int Multiplicacion = 39;
  public static final int Write = 43;
  public static final int Numero = 32;
  public static final int Main = 30;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Linea",
  "Int",
  "Break",
  "Case",
  "Char",
  "Const",
  "Coma",
  "Continue",
  "Default",
  "Do",
  "For",
  "Long",
  "Return",
  "Short",
  "Switch",
  "Void",
  "While",
  "If",
  "Else",
  "Relacionales",
  "Identificador",
  "Literal",
  "Parentesis_a",
  "Parentesis_c",
  "Corchete_a",
  "Corchete_c",
  "Llave_a",
  "Llave_c",
  "Main",
  "Scolon",
  "Numero",
  "Asignacion",
  "Or",
  "And",
  "Not",
  "Mas",
  "Menos",
  "Multiplicacion",
  "Division",
  "Modulo",
  "Unarios",
  "Write",
  "Read",
  "Dos_puntos",
  "LEX_ERROR"
  };
}

