/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Toolkit;
import javax.swing.JButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextArea;

/**
 *
 * @author Feterro
 */
public class TablaTokens extends javax.swing.JFrame {

    /**
     * Creates new form tablaTokens
     */
    
    
    public TablaTokens() {
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_Tokens = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_Errores = new javax.swing.JTable();
        btn_Archivo = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabla_Errores1 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabla_Tokens1 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        tabla_Errores2 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        codigo_e = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("gatito.png")));
        setResizable(false);
        setSize(new java.awt.Dimension(811, 554));

        jTabbedPane1.setBackground(new java.awt.Color(153, 153, 153));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(1, 0, 19));
        jPanel1.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        jPanel1.setLayout(null);

        tabla_Tokens.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tabla_Tokens.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        tabla_Tokens.setForeground(new java.awt.Color(0, 0, 0));
        tabla_Tokens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Token", "Tipo", "Lineas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_Tokens.setGridColor(new java.awt.Color(51, 51, 51));
        tabla_Tokens.setRowHeight(25);
        tabla_Tokens.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabla_Tokens);
        if (tabla_Tokens.getColumnModel().getColumnCount() > 0) {
            tabla_Tokens.getColumnModel().getColumn(0).setResizable(false);
            tabla_Tokens.getColumnModel().getColumn(1).setResizable(false);
            tabla_Tokens.getColumnModel().getColumn(1).setHeaderValue("Tipo");
            tabla_Tokens.getColumnModel().getColumn(2).setResizable(false);
            tabla_Tokens.getColumnModel().getColumn(2).setHeaderValue("Lineas");
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(60, 130, 669, 480);

        tabla_Errores.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        tabla_Errores.setForeground(new java.awt.Color(0, 0, 0));
        tabla_Errores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Error", "Linea"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_Errores.setGridColor(new java.awt.Color(51, 51, 51));
        tabla_Errores.setRowHeight(24);
        tabla_Errores.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tabla_Errores);
        if (tabla_Errores.getColumnModel().getColumnCount() > 0) {
            tabla_Errores.getColumnModel().getColumn(0).setResizable(false);
            tabla_Errores.getColumnModel().getColumn(1).setResizable(false);
            tabla_Errores.getColumnModel().getColumn(1).setHeaderValue("Linea");
        }

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(800, 130, 650, 480);

        btn_Archivo.setBackground(new java.awt.Color(22, 49, 87));
        btn_Archivo.setFont(new java.awt.Font("sansserif", 0, 21)); // NOI18N
        btn_Archivo.setForeground(new java.awt.Color(255, 255, 255));
        btn_Archivo.setText("Cargar archivo");
        btn_Archivo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_Archivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ArchivoActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Archivo);
        btn_Archivo.setBounds(1107, 646, 240, 60);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/gato.png"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(1370, 630, 80, 90);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/gatito (1).png"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(220, 30, 80, 90);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Scanner Léxico");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 20, 811, 77);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Errores Léxicos");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jLabel3);
        jLabel3.setBounds(710, 20, 811, 77);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/gatito (3).png"))); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(930, 30, 80, 90);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/sean-sinclair-gai1YB3UmDA-unsplash.jpg"))); // NOI18N
        jLabel8.setText("Scanner Para");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(-620, -410, 2230, 1180);

        jTabbedPane1.addTab("Scanner", jPanel1);

        jPanel2.setBackground(new java.awt.Color(1, 0, 19));
        jPanel2.setLayout(null);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/gatito (4).png"))); // NOI18N
        jPanel2.add(jLabel13);
        jLabel13.setBounds(200, 30, 80, 90);

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Código");
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel11);
        jLabel11.setBounds(230, 70, 210, 30);

        tabla_Errores1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        tabla_Errores1.setForeground(new java.awt.Color(0, 0, 0));
        tabla_Errores1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Error Sintáctico"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_Errores1.setGridColor(new java.awt.Color(51, 51, 51));
        tabla_Errores1.setRowHeight(24);
        tabla_Errores1.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(tabla_Errores1);

        jPanel2.add(jScrollPane4);
        jScrollPane4.setBounds(660, 130, 810, 230);

        tabla_Tokens1.setEditable(false);
        tabla_Tokens1.setBackground(new java.awt.Color(255, 255, 255));
        tabla_Tokens1.setColumns(20);
        tabla_Tokens1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        tabla_Tokens1.setRows(5);
        jScrollPane5.setViewportView(tabla_Tokens1);

        jPanel2.add(jScrollPane5);
        jScrollPane5.setBounds(60, 130, 540, 480);

        tabla_Errores2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        tabla_Errores2.setForeground(new java.awt.Color(0, 0, 0));
        tabla_Errores2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Error Semántico"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_Errores2.setGridColor(new java.awt.Color(51, 51, 51));
        tabla_Errores2.setRowHeight(24);
        tabla_Errores2.getTableHeader().setReorderingAllowed(false);
        jScrollPane6.setViewportView(tabla_Errores2);

        jPanel2.add(jScrollPane6);
        jScrollPane6.setBounds(660, 380, 810, 230);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/sean-sinclair-gai1YB3UmDA-unsplash.jpg"))); // NOI18N
        jLabel5.setText("Scanner Para");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(0, 0, 1570, 760);

        jTabbedPane1.addTab("Análisis", jPanel2);

        jPanel3.setBackground(new java.awt.Color(1, 0, 19));
        jPanel3.setLayout(null);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/WhatsApp Image 2021-06-27 at 18.25.38.jpeg"))); // NOI18N
        jPanel3.add(jLabel14);
        jLabel14.setBounds(850, 120, 540, 480);

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Código Ensamblador");
        jLabel12.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel3.add(jLabel12);
        jLabel12.setBounds(140, 80, 540, 30);

        codigo_e.setEditable(false);
        codigo_e.setBackground(new java.awt.Color(255, 255, 255));
        codigo_e.setColumns(20);
        codigo_e.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        codigo_e.setRows(5);
        jScrollPane8.setViewportView(codigo_e);

        jPanel3.add(jScrollPane8);
        jScrollPane8.setBounds(150, 120, 540, 480);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/gatito (2).png"))); // NOI18N
        jPanel3.add(jLabel15);
        jLabel15.setBounds(200, 40, 80, 90);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/sean-sinclair-gai1YB3UmDA-unsplash.jpg"))); // NOI18N
        jLabel10.setText("Scanner Para");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(0, 0, 1570, 760);

        jTabbedPane1.addTab("Código", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1521, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 761, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ArchivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ArchivoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TablaTokens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TablaTokens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TablaTokens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TablaTokens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TablaTokens().setVisible(true);
            }
        });
    
    }

    public JButton getBtn_Archivo() {
        return btn_Archivo;
    }

    public JTable getTabla_Errores() {
        return tabla_Errores;
    }

    public JTable getTabla_Errores1() {
        return tabla_Errores1;
    }

    public JTable getTabla_Errores2() {
        return tabla_Errores2;
    }

    public JTable getTabla_Tokens() {
        return tabla_Tokens;
    }

    public JTextArea getTabla_Tokens1() {
        return tabla_Tokens1;
    }

    public JTextArea getCodigo_e() {
        return codigo_e;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_Archivo;
    public javax.swing.JTextArea codigo_e;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JTable tabla_Errores;
    public javax.swing.JTable tabla_Errores1;
    public javax.swing.JTable tabla_Errores2;
    public javax.swing.JTable tabla_Tokens;
    public javax.swing.JTextArea tabla_Tokens1;
    // End of variables declaration//GEN-END:variables
}
