/* The following code was generated by JFlex 1.4.3 on 24/05/21 18:59 */

package Scanner;
import TokenTypes.Symbols;
import java_cup.runtime.Symbol;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 24/05/21 18:59 from the specification file
 * <tt>E:/ArchivosTec/Quintosemestre/Compi/CScannerCompi2021/ScannerCompile/src/Scanner/LexerCup.flex</tt>
 */
class LexerCup {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\1\1\12\2\0\1\1\22\0\1\26\1\33\1\13\1\0"+
    "\1\2\1\32\1\34\1\15\1\20\1\21\1\17\1\24\1\1\1\6"+
    "\1\0\1\16\1\4\3\5\4\5\2\3\1\0\1\57\1\33\1\30"+
    "\1\33\2\0\6\10\5\2\1\11\13\2\1\7\2\2\1\60\1\0"+
    "\1\61\1\0\1\2\1\0\1\43\1\40\1\45\1\52\1\42\1\14"+
    "\1\54\1\47\1\35\1\2\1\44\1\53\1\2\1\36\1\50\2\2"+
    "\1\41\1\46\1\37\1\51\1\56\1\55\1\7\2\2\1\22\1\27"+
    "\1\23\163\0\1\0\u1f2a\0\1\25\1\31\udfe2\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\2\4\1\1\1\5\1\1"+
    "\1\3\1\1\1\6\1\1\1\7\1\10\1\11\1\12"+
    "\3\1\1\6\1\13\1\1\12\3\1\14\1\15\1\16"+
    "\1\0\1\4\1\0\1\4\1\17\2\4\4\0\1\3"+
    "\1\0\1\2\2\0\1\13\1\20\12\3\1\21\3\3"+
    "\3\0\2\17\1\4\1\0\1\4\1\22\4\0\1\23"+
    "\14\3\1\0\1\17\1\4\1\0\1\24\1\0\1\17"+
    "\2\0\2\3\1\25\1\26\1\27\5\3\1\30\1\3"+
    "\1\31\1\32\1\17\2\0\1\33\2\3\1\34\1\35"+
    "\2\3\1\36\2\0\1\37\1\3\1\40\1\3\1\0"+
    "\1\3\1\41\1\0\1\42\10\0";

  private static int [] zzUnpackAction() {
    int [] result = new int[147];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\62\0\144\0\226\0\310\0\372\0\u012c\0\62"+
    "\0\u015e\0\u0190\0\u01c2\0\u01f4\0\u0226\0\u0258\0\62\0\62"+
    "\0\62\0\u028a\0\u02bc\0\u02ee\0\62\0\u02ee\0\u0320\0\u0352"+
    "\0\u0384\0\u03b6\0\u03e8\0\u041a\0\u044c\0\u047e\0\u04b0\0\u04e2"+
    "\0\u0514\0\62\0\62\0\62\0\u0546\0\u0578\0\u05aa\0\u05dc"+
    "\0\u060e\0\u0640\0\u0672\0\u06a4\0\u06d6\0\u0708\0\u073a\0\u076c"+
    "\0\u079e\0\u07d0\0\u0802\0\u0834\0\62\0\226\0\u0866\0\u0898"+
    "\0\u08ca\0\u08fc\0\u092e\0\u0960\0\u0992\0\u09c4\0\u09f6\0\u0a28"+
    "\0\226\0\u0a5a\0\u0a8c\0\u0abe\0\u0af0\0\u0b22\0\u0b54\0\u0b86"+
    "\0\u05dc\0\u0bb8\0\u0bea\0\62\0\226\0\u0c1c\0\u0c4e\0\u0c80"+
    "\0\u0cb2\0\226\0\u0ce4\0\u0d16\0\u0d48\0\u0d7a\0\u0dac\0\u0dde"+
    "\0\u0e10\0\u0e42\0\u0e74\0\u0ea6\0\u0ed8\0\u0f0a\0\u0f3c\0\u0f6e"+
    "\0\u0fa0\0\u0fd2\0\62\0\u1004\0\62\0\u1036\0\u1068\0\u109a"+
    "\0\u10cc\0\226\0\226\0\226\0\u10fe\0\u1130\0\u1162\0\u1194"+
    "\0\u11c6\0\226\0\u11f8\0\226\0\u122a\0\u125c\0\u128e\0\u12c0"+
    "\0\226\0\u12f2\0\u1324\0\226\0\226\0\u1356\0\u1388\0\226"+
    "\0\u13ba\0\u13ec\0\226\0\u141e\0\226\0\u1450\0\u1482\0\u14b4"+
    "\0\226\0\u14e6\0\226\0\u1518\0\u154a\0\u157c\0\u15ae\0\u15e0"+
    "\0\u1612\0\u1644\0\u1676";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[147];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\5\1\7\3\4"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\2\1\3\1\23\1\24\1\2"+
    "\1\25\1\26\1\27\1\30\2\4\1\31\1\32\1\33"+
    "\2\4\1\34\1\35\3\4\1\36\1\37\1\4\1\40"+
    "\1\41\1\42\1\43\1\44\63\0\1\3\24\0\1\3"+
    "\35\0\4\4\1\45\3\4\2\0\1\4\20\0\22\4"+
    "\6\0\1\5\1\46\1\5\1\47\2\0\1\50\41\0"+
    "\1\50\11\0\1\51\1\52\1\53\1\47\1\54\1\0"+
    "\1\50\41\0\1\50\12\0\1\55\1\0\1\56\21\0"+
    "\1\25\31\0\12\57\1\0\47\57\2\0\4\4\1\45"+
    "\3\4\2\0\1\4\20\0\13\4\1\60\6\4\3\0"+
    "\12\61\1\0\47\61\16\0\1\62\1\63\10\0\1\25"+
    "\61\0\1\25\37\0\1\64\12\0\1\25\64\0\1\25"+
    "\3\0\1\25\60\0\1\65\62\0\1\65\65\0\1\65"+
    "\27\0\4\4\1\45\3\4\2\0\1\66\20\0\1\4"+
    "\1\67\20\4\5\0\4\4\1\45\3\4\2\0\1\4"+
    "\20\0\4\4\1\70\15\4\5\0\4\4\1\45\3\4"+
    "\2\0\1\4\20\0\5\4\1\71\14\4\5\0\4\4"+
    "\1\45\3\4\2\0\1\4\20\0\16\4\1\72\3\4"+
    "\5\0\4\4\1\45\3\4\2\0\1\4\20\0\6\4"+
    "\1\73\3\4\1\74\1\75\6\4\5\0\4\4\1\45"+
    "\3\4\2\0\1\4\20\0\12\4\1\76\5\4\1\77"+
    "\1\4\5\0\4\4\1\45\3\4\2\0\1\4\20\0"+
    "\5\4\1\100\5\4\1\101\6\4\5\0\4\4\1\45"+
    "\3\4\2\0\1\4\20\0\13\4\1\102\6\4\5\0"+
    "\4\4\1\45\3\4\2\0\1\4\20\0\12\4\1\103"+
    "\7\4\5\0\4\4\1\45\3\4\2\0\1\4\20\0"+
    "\13\4\1\104\6\4\7\0\1\105\60\0\1\5\1\46"+
    "\1\5\1\47\1\106\1\0\1\50\41\0\1\50\12\0"+
    "\1\107\60\0\1\51\1\110\1\51\1\47\56\0\1\51"+
    "\1\110\1\51\1\47\2\0\1\111\41\0\1\111\11\0"+
    "\1\51\1\52\1\53\1\47\1\106\1\0\1\50\41\0"+
    "\1\50\11\0\1\51\1\52\1\53\1\47\2\0\1\50"+
    "\41\0\1\50\11\0\3\112\2\0\1\112\60\0\1\54"+
    "\77\0\1\113\34\0\13\57\1\114\46\57\2\0\4\4"+
    "\1\45\3\4\2\0\1\4\20\0\4\4\1\115\15\4"+
    "\3\0\15\61\1\114\44\61\12\62\1\0\47\62\17\63"+
    "\1\116\42\63\3\0\1\117\1\120\1\117\1\121\55\0"+
    "\4\4\1\45\3\4\2\0\1\4\20\0\2\4\1\122"+
    "\17\4\5\0\4\4\1\45\3\4\2\0\1\4\20\0"+
    "\5\4\1\123\14\4\5\0\4\4\1\45\3\4\2\0"+
    "\1\4\20\0\2\4\1\124\17\4\5\0\4\4\1\45"+
    "\3\4\2\0\1\4\20\0\11\4\1\125\10\4\5\0"+
    "\4\4\1\45\3\4\2\0\1\4\20\0\11\4\1\126"+
    "\10\4\5\0\4\4\1\45\3\4\2\0\1\4\20\0"+
    "\6\4\1\127\13\4\5\0\4\4\1\45\3\4\2\0"+
    "\1\4\20\0\1\4\1\130\20\4\5\0\4\4\1\45"+
    "\3\4\2\0\1\4\20\0\13\4\1\131\6\4\5\0"+
    "\4\4\1\45\3\4\2\0\1\4\20\0\1\132\21\4"+
    "\5\0\4\4\1\45\3\4\2\0\1\133\20\0\22\4"+
    "\5\0\4\4\1\45\3\4\2\0\1\4\20\0\1\4"+
    "\1\134\20\4\5\0\4\4\1\45\3\4\2\0\1\4"+
    "\20\0\1\135\21\4\5\0\4\4\1\45\3\4\2\0"+
    "\1\4\20\0\1\136\21\4\12\0\1\137\55\0\3\140"+
    "\2\0\1\140\60\0\1\106\55\0\1\51\1\110\1\51"+
    "\1\47\1\106\1\0\1\111\41\0\1\111\11\0\1\112"+
    "\1\141\1\112\1\47\1\0\1\112\1\50\41\0\1\50"+
    "\34\0\1\142\33\0\16\63\1\143\1\116\42\63\3\0"+
    "\1\117\1\120\1\117\1\121\2\0\1\144\7\0\1\145"+
    "\31\0\1\144\11\0\1\117\1\120\1\117\1\121\1\146"+
    "\1\0\1\144\7\0\1\145\31\0\1\144\12\0\1\147"+
    "\57\0\4\4\1\45\3\4\2\0\1\4\20\0\6\4"+
    "\1\150\13\4\5\0\4\4\1\45\3\4\2\0\1\4"+
    "\20\0\14\4\1\151\5\4\5\0\4\4\1\45\3\4"+
    "\2\0\1\4\20\0\5\4\1\152\14\4\5\0\4\4"+
    "\1\45\3\4\2\0\1\4\20\0\5\4\1\153\14\4"+
    "\5\0\4\4\1\45\3\4\2\0\1\4\20\0\4\4"+
    "\1\154\15\4\5\0\4\4\1\45\3\4\2\0\1\4"+
    "\20\0\2\4\1\155\6\4\1\156\10\4\5\0\4\4"+
    "\1\45\3\4\2\0\1\4\20\0\4\4\1\157\15\4"+
    "\5\0\4\4\1\45\3\4\2\0\1\4\20\0\2\4"+
    "\1\160\17\4\5\0\4\4\1\45\3\4\2\0\1\4"+
    "\20\0\6\4\1\161\13\4\5\0\4\4\1\45\3\4"+
    "\2\0\1\4\20\0\17\4\1\162\2\4\5\0\4\4"+
    "\1\45\3\4\2\0\1\4\20\0\16\4\1\163\3\4"+
    "\5\0\4\4\1\45\3\4\2\0\1\4\20\0\15\4"+
    "\1\164\4\4\6\0\3\165\2\0\1\165\54\0\1\140"+
    "\1\166\1\140\1\47\1\0\1\140\1\111\41\0\1\111"+
    "\11\0\1\112\1\141\1\112\1\47\1\106\1\112\1\50"+
    "\41\0\1\50\35\0\1\167\35\0\1\117\1\120\1\117"+
    "\1\121\12\0\1\145\43\0\3\170\2\0\1\170\60\0"+
    "\1\146\54\0\4\4\1\45\3\4\2\0\1\4\20\0"+
    "\7\4\1\171\12\4\5\0\4\4\1\45\3\4\2\0"+
    "\1\4\20\0\4\4\1\172\15\4\5\0\4\4\1\45"+
    "\3\4\2\0\1\4\20\0\1\173\21\4\5\0\4\4"+
    "\1\45\3\4\2\0\1\4\20\0\2\4\1\174\17\4"+
    "\5\0\4\4\1\45\3\4\2\0\1\4\20\0\2\4"+
    "\1\175\17\4\5\0\4\4\1\45\3\4\2\0\1\4"+
    "\20\0\10\4\1\176\11\4\5\0\4\4\1\45\3\4"+
    "\2\0\1\4\20\0\14\4\1\177\5\4\5\0\4\4"+
    "\1\45\3\4\2\0\1\4\20\0\5\4\1\200\14\4"+
    "\5\0\4\165\1\45\3\165\2\0\1\165\20\0\22\165"+
    "\6\0\1\140\1\166\1\140\1\47\1\106\1\140\1\111"+
    "\41\0\1\111\34\0\1\201\36\0\1\170\1\202\1\170"+
    "\1\121\1\0\1\170\1\144\7\0\1\145\31\0\1\144"+
    "\10\0\4\4\1\45\3\4\2\0\1\4\20\0\1\4"+
    "\1\203\20\4\5\0\4\4\1\45\3\4\2\0\1\4"+
    "\20\0\1\4\1\204\20\4\5\0\4\4\1\45\3\4"+
    "\2\0\1\4\20\0\12\4\1\205\7\4\5\0\4\4"+
    "\1\45\3\4\2\0\1\4\20\0\16\4\1\206\3\4"+
    "\33\0\1\207\34\0\1\170\1\202\1\170\1\121\1\146"+
    "\1\170\1\144\7\0\1\145\31\0\1\144\10\0\4\4"+
    "\1\45\3\4\2\0\1\4\20\0\14\4\1\210\5\4"+
    "\5\0\4\4\1\45\3\4\2\0\1\4\20\0\2\4"+
    "\1\211\17\4\31\0\1\212\35\0\4\4\1\45\3\4"+
    "\2\0\1\4\20\0\5\4\1\213\14\4\32\0\1\214"+
    "\60\0\1\215\61\0\1\216\62\0\1\217\60\0\1\220"+
    "\41\0\1\221\17\0\1\216\61\0\1\222\2\0\1\25"+
    "\57\0\1\223\60\0\1\221\33\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5800];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\5\1\1\11\6\1\3\11\3\1\1\11"+
    "\14\1\3\11\1\0\1\1\1\0\4\1\4\0\1\1"+
    "\1\0\1\1\2\0\1\11\17\1\3\0\3\1\1\0"+
    "\1\11\1\1\4\0\15\1\1\0\2\1\1\0\1\11"+
    "\1\0\1\11\2\0\17\1\2\0\10\1\2\0\4\1"+
    "\1\0\2\1\1\0\1\1\10\0";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[147];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    private Symbol symbol(int type, Object value){
        return new Symbol(type, yyline, yycolumn, value);
    }
    private Symbol symbol(int type){
        return new Symbol(type, yyline, yycolumn);
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  LexerCup(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  LexerCup(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 154) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 23: 
          { return new Symbol(sym.Char,yychar,yyline,yytext());
          }
        case 35: break;
        case 8: 
          { return new Symbol(sym.Parentesis_c,yychar,yyline,yytext());
          }
        case 36: break;
        case 12: 
          { return new Symbol(sym.Scolon,yychar,yyline,yytext());
          }
        case 37: break;
        case 10: 
          { return new Symbol(sym.Llave_c,yychar,yyline,yytext());
          }
        case 38: break;
        case 24: 
          { return new Symbol(sym.Long,yychar,yyline,yytext());
          }
        case 39: break;
        case 34: 
          { return new Symbol(sym.Continue,yychar,yyline,yytext());
          }
        case 40: break;
        case 17: 
          { return new Symbol(sym.Do,yychar,yyline,yytext());
          }
        case 41: break;
        case 13: 
          { return new Symbol(sym.Corchete_a, yychar, yyline, yytext());
          }
        case 42: break;
        case 21: 
          { return new Symbol(sym.Else,yychar,yyline,yytext());
          }
        case 43: break;
        case 5: 
          { return new Symbol(sym.Linea,yychar,yyline,yytext);
          }
        case 44: break;
        case 29: 
          { return new Symbol(sym.Short,yychar,yyline,yytext());
          }
        case 45: break;
        case 32: 
          { return new Symbol(sym.Switch,yychar,yyline,yytext());
          }
        case 46: break;
        case 6: 
          { return new Symbol(Symbols.Aritmeticos,yychar,yyline,yytext());
          }
        case 47: break;
        case 4: 
          { return new Literal(yyline,yytext());
          }
        case 48: break;
        case 30: 
          { return new Symbol(sym.While,yychar,yyline,yytext());
          }
        case 49: break;
        case 14: 
          { return new Symbol(sym.Corchete_c, yychar, yyline, yytext());
          }
        case 50: break;
        case 11: 
          { return new Symbol(Symbols.Relacionales,yychar,yyline,yytext());
          }
        case 51: break;
        case 15: 
          { return new Symbol(sym.Numero, yychar, yyline, yytext());
          }
        case 52: break;
        case 33: 
          { return new Symbol(sym.Default,yychar,yyline,yytext());
          }
        case 53: break;
        case 22: 
          { return new Symbol(sym.Case,yychar,yyline,yytext());
          }
        case 54: break;
        case 1: 
          { return new ErrorLexico(yyline,yytext());
          }
        case 55: break;
        case 25: 
          { return new Symbol(sym.Void,yychar,yyline,yytext());
          }
        case 56: break;
        case 16: 
          { return new Symbol(sym.If,yychar,yyline,yytext());
          }
        case 57: break;
        case 27: 
          { return new Symbol(sym.Break,yychar,yyline,yytext());
          }
        case 58: break;
        case 20: 
          { System.out.println("Bloque de comentarios");
          }
        case 59: break;
        case 19: 
          { return new Symbol(sym.Int,yychar,yyline,yytext());
          }
        case 60: break;
        case 28: 
          { return new Symbol(sym.Const,yychar,yyline,yytext());
          }
        case 61: break;
        case 3: 
          { return new Symbol(sym.Identificador,yychar,yyline,yytext());
          }
        case 62: break;
        case 18: 
          { return new Symbol(sym.For,yychar,yyline,yytext());
          }
        case 63: break;
        case 26: 
          { return new Symbol(sym.Identificador, yychar, yyline, yytext());
          }
        case 64: break;
        case 7: 
          { return new Symbol(sym.Parentesis_a,yychar,yyline,yytext());
          }
        case 65: break;
        case 2: 
          { /*Ignore*/
          }
        case 66: break;
        case 31: 
          { return new Symbol(sym.Return,yychar,yyline,yytext());
          }
        case 67: break;
        case 9: 
          { return new Symbol(sym.Llave_a,yychar,yyline,yytext());
          }
        case 68: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
