/* The following code was generated by JFlex 1.4.3 on 20/4/21 20:27 */

package Scanner;
import TokenTypes.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 20/4/21 20:27 from the specification file
 * <tt>C:/Users/Laptop/OneDrive/Documentos/Quinto Semestre/COMPILADORES E INTERPRETES/CScannerCompi2021/ScannerCompile/src/Scanner/Lexer.flex</tt>
 */
class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\1\1\16\2\0\1\1\22\0\1\1\1\54\1\15\1\0"+
    "\1\14\1\54\1\56\1\0\1\61\1\62\1\57\1\50\1\1\1\11"+
    "\1\12\1\60\1\2\3\4\4\4\2\3\1\47\1\47\1\53\1\51"+
    "\1\52\1\47\1\0\3\6\1\13\1\10\1\13\5\14\1\7\13\14"+
    "\1\5\2\14\1\63\1\0\1\64\1\54\1\14\1\0\1\22\1\17"+
    "\1\31\1\35\1\27\1\20\1\41\1\33\1\34\1\14\1\30\1\36"+
    "\1\37\1\21\1\25\1\45\1\14\1\26\1\32\1\24\1\23\1\46"+
    "\1\43\1\40\1\44\1\42\1\65\1\55\1\66\1\47\uff81\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\2\3\1\4\2\5\1\1\1\6"+
    "\17\4\10\5\3\1\1\3\2\0\1\3\1\0\1\3"+
    "\1\0\20\4\1\7\1\4\1\7\4\4\1\0\2\3"+
    "\1\0\30\4\1\0\16\4\1\10\11\4";

  private static int [] zzUnpackAction() {
    int [] result = new int[119];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\67\0\156\0\245\0\334\0\u0113\0\u014a\0\u0181"+
    "\0\u01b8\0\67\0\u01ef\0\u0226\0\u025d\0\u0294\0\u02cb\0\u0302"+
    "\0\u0339\0\u0370\0\u03a7\0\u03de\0\u0415\0\u044c\0\u0483\0\u04ba"+
    "\0\u04f1\0\67\0\u0528\0\u055f\0\u0596\0\u05cd\0\u0604\0\u063b"+
    "\0\u0672\0\u06a9\0\u06e0\0\u0717\0\u074e\0\u0785\0\u07bc\0\67"+
    "\0\u07f3\0\u082a\0\u0861\0\u0898\0\u08cf\0\u0906\0\u093d\0\u0974"+
    "\0\u09ab\0\u09e2\0\u0a19\0\u0a50\0\u0a87\0\u0abe\0\u0af5\0\u0b2c"+
    "\0\u0b63\0\u0b9a\0\u0bd1\0\u0113\0\u0c08\0\u0c3f\0\u0c76\0\u0cad"+
    "\0\u0ce4\0\u0d1b\0\u0d52\0\u0d89\0\u0dc0\0\u0df7\0\u0e2e\0\u0e65"+
    "\0\u0e9c\0\u0ed3\0\u0f0a\0\u0f41\0\u0f78\0\u0faf\0\u0fe6\0\u101d"+
    "\0\u1054\0\u108b\0\u10c2\0\u10f9\0\u1130\0\u1167\0\u119e\0\u11d5"+
    "\0\u120c\0\u1243\0\u127a\0\u12b1\0\u12e8\0\u131f\0\u1356\0\u138d"+
    "\0\u13c4\0\u13fb\0\u1432\0\u1469\0\u14a0\0\u14d7\0\u150e\0\u1545"+
    "\0\u157c\0\u15b3\0\u15ea\0\u1621\0\u1658\0\67\0\u168f\0\u16c6"+
    "\0\u16fd\0\u1734\0\u176b\0\u17a2\0\u17d9\0\u1810\0\u1847";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[119];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\2\5\4\6\1\7\1\10\2\6"+
    "\1\11\1\12\1\13\1\14\1\6\1\15\1\16\1\17"+
    "\1\6\1\20\1\21\1\6\1\22\1\23\1\6\1\24"+
    "\1\25\1\26\2\6\1\27\1\6\1\30\2\6\1\31"+
    "\1\32\1\33\1\34\1\35\1\36\1\34\1\37\1\40"+
    "\1\34\1\41\1\42\1\2\1\43\1\2\1\44\1\2"+
    "\70\0\1\3\67\0\1\45\1\46\1\45\1\47\1\0"+
    "\1\50\1\51\1\0\1\52\1\50\4\0\1\50\6\0"+
    "\1\51\5\0\2\50\1\0\1\47\30\0\3\5\2\0"+
    "\1\50\1\51\1\0\1\52\1\50\4\0\1\50\6\0"+
    "\1\51\5\0\2\50\32\0\7\6\2\0\2\6\2\0"+
    "\30\6\31\0\1\32\37\0\2\32\16\0\3\52\62\0"+
    "\16\53\1\0\50\53\2\0\7\6\2\0\2\6\2\0"+
    "\7\6\1\54\20\6\22\0\7\6\2\0\2\6\2\0"+
    "\6\6\1\55\10\6\1\56\10\6\22\0\7\6\2\0"+
    "\2\6\2\0\4\6\1\57\23\6\22\0\7\6\2\0"+
    "\2\6\2\0\2\6\1\60\25\6\22\0\7\6\2\0"+
    "\2\6\2\0\25\6\1\61\2\6\22\0\7\6\2\0"+
    "\2\6\2\0\10\6\1\62\17\6\22\0\7\6\2\0"+
    "\2\6\2\0\2\6\1\63\14\6\1\64\1\6\1\65"+
    "\6\6\22\0\7\6\2\0\2\6\2\0\3\6\1\64"+
    "\2\6\1\66\5\6\1\67\13\6\22\0\7\6\2\0"+
    "\2\6\2\0\5\6\1\70\6\6\1\71\1\72\6\6"+
    "\1\73\3\6\22\0\7\6\2\0\2\6\2\0\1\6"+
    "\1\74\1\75\25\6\22\0\7\6\2\0\2\6\2\0"+
    "\6\6\1\76\1\6\1\77\17\6\22\0\7\6\2\0"+
    "\2\6\2\0\6\6\1\100\21\6\22\0\7\6\2\0"+
    "\2\6\2\0\6\6\1\57\21\6\22\0\7\6\2\0"+
    "\2\6\2\0\14\6\1\101\13\6\22\0\7\6\2\0"+
    "\2\6\2\0\6\6\1\102\21\6\70\0\2\32\66\0"+
    "\1\32\66\0\1\32\1\34\65\0\1\32\1\0\1\34"+
    "\64\0\1\32\3\0\1\32\62\0\1\32\4\0\1\32"+
    "\61\0\1\32\5\0\1\103\71\0\1\32\70\0\1\32"+
    "\70\0\1\32\2\0\1\45\1\46\1\45\2\0\1\50"+
    "\1\51\1\0\1\52\1\50\4\0\1\50\6\0\1\51"+
    "\5\0\2\50\32\0\3\46\3\0\1\51\1\0\1\52"+
    "\1\50\4\0\1\50\6\0\1\51\5\0\1\50\33\0"+
    "\3\104\1\0\1\104\1\0\1\104\2\0\1\104\3\0"+
    "\2\104\1\0\1\104\4\0\1\104\1\0\1\104\3\0"+
    "\1\104\33\0\3\105\4\0\1\106\36\0\1\106\20\0"+
    "\3\52\3\0\1\51\2\0\1\50\4\0\1\50\6\0"+
    "\1\51\5\0\1\50\31\0\15\53\1\50\51\53\2\0"+
    "\7\6\2\0\2\6\2\0\10\6\1\107\17\6\22\0"+
    "\7\6\2\0\2\6\2\0\7\6\1\74\20\6\22\0"+
    "\7\6\2\0\2\6\2\0\6\6\1\110\21\6\22\0"+
    "\7\6\2\0\2\6\2\0\5\6\1\111\22\6\22\0"+
    "\7\6\2\0\2\6\2\0\13\6\1\112\1\6\1\113"+
    "\12\6\22\0\7\6\2\0\2\6\2\0\26\6\1\114"+
    "\1\6\22\0\7\6\2\0\2\6\2\0\5\6\1\115"+
    "\14\6\1\116\5\6\22\0\7\6\2\0\2\6\2\0"+
    "\4\6\1\117\23\6\22\0\7\6\2\0\2\6\2\0"+
    "\13\6\1\120\14\6\22\0\7\6\2\0\2\6\2\0"+
    "\5\6\1\121\22\6\22\0\7\6\2\0\2\6\2\0"+
    "\2\6\1\122\25\6\22\0\7\6\2\0\2\6\2\0"+
    "\3\6\1\55\24\6\22\0\7\6\2\0\2\6\2\0"+
    "\3\6\1\123\3\6\1\124\20\6\22\0\7\6\2\0"+
    "\2\6\2\0\6\6\1\125\21\6\22\0\7\6\2\0"+
    "\2\6\2\0\22\6\1\126\1\127\4\6\22\0\7\6"+
    "\2\0\2\6\2\0\15\6\1\130\12\6\22\0\7\6"+
    "\2\0\2\6\2\0\5\6\1\74\22\6\22\0\7\6"+
    "\2\0\2\6\2\0\4\6\1\131\23\6\22\0\7\6"+
    "\2\0\2\6\2\0\1\6\1\132\26\6\22\0\7\6"+
    "\2\0\2\6\2\0\2\6\1\133\25\6\22\0\7\6"+
    "\2\0\2\6\2\0\15\6\1\134\12\6\22\0\7\6"+
    "\2\0\2\6\2\0\15\6\1\135\1\6\1\136\10\6"+
    "\20\0\57\103\1\137\7\103\2\0\3\104\1\0\1\104"+
    "\1\50\1\104\2\0\1\104\3\0\2\104\1\0\1\104"+
    "\4\0\1\104\1\0\1\104\3\0\1\104\1\50\32\0"+
    "\3\105\6\0\1\50\4\0\1\50\14\0\1\50\33\0"+
    "\3\105\64\0\7\6\2\0\2\6\2\0\3\6\1\140"+
    "\24\6\22\0\7\6\2\0\2\6\2\0\3\6\1\75"+
    "\24\6\22\0\7\6\2\0\2\6\2\0\6\6\1\74"+
    "\21\6\22\0\7\6\2\0\2\6\2\0\15\6\1\141"+
    "\12\6\22\0\7\6\2\0\2\6\2\0\6\6\1\142"+
    "\21\6\22\0\7\6\2\0\2\6\2\0\10\6\1\143"+
    "\17\6\22\0\7\6\2\0\2\6\2\0\4\6\1\144"+
    "\23\6\22\0\7\6\2\0\2\6\2\0\15\6\1\145"+
    "\12\6\22\0\7\6\2\0\2\6\2\0\20\6\1\74"+
    "\7\6\22\0\7\6\2\0\2\6\2\0\10\6\1\74"+
    "\17\6\22\0\7\6\2\0\2\6\2\0\10\6\1\144"+
    "\17\6\22\0\7\6\2\0\2\6\2\0\5\6\1\146"+
    "\5\6\1\75\14\6\22\0\7\6\2\0\2\6\2\0"+
    "\5\6\1\147\22\6\22\0\7\6\2\0\2\6\2\0"+
    "\4\6\1\150\23\6\22\0\7\6\2\0\2\6\2\0"+
    "\7\6\1\75\20\6\22\0\7\6\2\0\2\6\2\0"+
    "\2\6\1\151\25\6\22\0\7\6\2\0\2\6\2\0"+
    "\10\6\1\152\17\6\22\0\7\6\2\0\2\6\2\0"+
    "\5\6\1\153\22\6\22\0\7\6\2\0\2\6\2\0"+
    "\1\134\27\6\22\0\7\6\2\0\2\6\2\0\3\6"+
    "\1\154\24\6\22\0\7\6\2\0\2\6\2\0\22\6"+
    "\1\74\5\6\22\0\7\6\2\0\2\6\2\0\17\6"+
    "\1\120\10\6\22\0\7\6\2\0\2\6\2\0\16\6"+
    "\1\74\11\6\22\0\7\6\2\0\2\6\2\0\3\6"+
    "\1\155\24\6\20\0\57\103\1\137\1\156\6\103\2\0"+
    "\7\6\2\0\2\6\2\0\11\6\1\74\16\6\22\0"+
    "\7\6\2\0\2\6\2\0\22\6\1\126\5\6\22\0"+
    "\7\6\2\0\2\6\2\0\2\6\1\74\25\6\22\0"+
    "\7\6\2\0\2\6\2\0\16\6\1\157\11\6\22\0"+
    "\7\6\2\0\2\6\2\0\7\6\1\142\20\6\22\0"+
    "\7\6\2\0\2\6\2\0\13\6\1\160\14\6\22\0"+
    "\7\6\2\0\2\6\2\0\15\6\1\161\12\6\22\0"+
    "\7\6\2\0\2\6\2\0\15\6\1\162\12\6\22\0"+
    "\7\6\2\0\2\6\2\0\12\6\1\75\15\6\22\0"+
    "\7\6\2\0\2\6\2\0\10\6\1\135\17\6\22\0"+
    "\7\6\2\0\2\6\2\0\6\6\1\163\21\6\22\0"+
    "\7\6\2\0\2\6\2\0\12\6\1\164\15\6\22\0"+
    "\7\6\2\0\2\6\2\0\4\6\1\165\23\6\22\0"+
    "\7\6\2\0\2\6\2\0\5\6\1\101\22\6\22\0"+
    "\7\6\2\0\2\6\2\0\10\6\1\163\17\6\22\0"+
    "\7\6\2\0\2\6\2\0\5\6\1\166\22\6\22\0"+
    "\7\6\2\0\2\6\2\0\2\6\1\167\25\6\22\0"+
    "\7\6\2\0\2\6\2\0\12\6\1\74\15\6\22\0"+
    "\7\6\2\0\2\6\2\0\1\6\1\74\26\6\22\0"+
    "\7\6\2\0\2\6\2\0\14\6\1\74\13\6\22\0"+
    "\7\6\2\0\2\6\2\0\17\6\1\75\10\6\22\0"+
    "\7\6\2\0\2\6\2\0\10\6\1\55\17\6\22\0"+
    "\7\6\2\0\2\6\2\0\4\6\1\120\23\6\20\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[6270];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\7\1\1\11\17\1\1\11\13\1\2\0"+
    "\1\11\1\0\1\1\1\0\27\1\1\0\2\1\1\0"+
    "\30\1\1\0\16\1\1\11\11\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[119];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    public String lexeme;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 158) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 2: 
          { /*Ignore*/
          }
        case 9: break;
        case 4: 
          { return new Identificador(yyline,yytext());
          }
        case 10: break;
        case 8: 
          { System.out.println("Bloque de comentarios");
          }
        case 11: break;
        case 5: 
          { return new Operador(yyline,yytext());
          }
        case 12: break;
        case 1: 
          { return new ErrorLexico(yyline,yytext());
          }
        case 13: break;
        case 3: 
          { return new Literal(yyline,yytext());
          }
        case 14: break;
        case 7: 
          { return new Reservadas(yyline,yytext());
          }
        case 15: break;
        case 6: 
          { yyline++;
          }
        case 16: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
