
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Scanner;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Else = 19;
  public static final int Continue = 8;
  public static final int Parentesis_c = 25;
  public static final int For = 11;
  public static final int Parentesis_a = 24;
  public static final int Char = 6;
  public static final int Numero = 31;
  public static final int Corchete_c = 27;
  public static final int Relacionales = 21;
  public static final int Corchete_a = 26;
  public static final int Break = 4;
  public static final int Identificador = 22;
  public static final int Int = 3;
  public static final int Default = 9;
  public static final int Llave_c = 29;
  public static final int Const = 7;
  public static final int Llave_a = 28;
  public static final int Short = 14;
  public static final int Aritmeticos = 20;
  public static final int EOF = 0;
  public static final int Case = 5;
  public static final int If = 18;
  public static final int Linea = 2;
  public static final int Return = 13;
  public static final int LEX_ERROR = 32;
  public static final int error = 1;
  public static final int Switch = 15;
  public static final int Do = 10;
  public static final int Void = 16;
  public static final int Scolon = 30;
  public static final int Literal = 23;
  public static final int While = 17;
  public static final int Long = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Linea",
  "Int",
  "Break",
  "Case",
  "Char",
  "Const",
  "Continue",
  "Default",
  "Do",
  "For",
  "Long",
  "Return",
  "Short",
  "Switch",
  "Void",
  "While",
  "If",
  "Else",
  "Aritmeticos",
  "Relacionales",
  "Identificador",
  "Literal",
  "Parentesis_a",
  "Parentesis_c",
  "Corchete_a",
  "Corchete_c",
  "Llave_a",
  "Llave_c",
  "Scolon",
  "Numero",
  "LEX_ERROR"
  };
}

